name: Syncing repos

on: push

jobs:
  first:
    name: Push to dreamhost
    runs-on: ubuntu-latest
    steps:
    - name: git status
      run: git status
    - name: get remotes
      run: git remote -v
    - name: set remote
      run: git remote set-url origin ${{ development.DREAMHOST_PATH}}